const CATEGORY_ORDER = ["早午餐", "午晚餐", "咖啡", "飲料", "酒吧", "景點", "購物"];
const DATA_VERSION = "20260711p";
const PLACE_SUMMARY_OVERRIDES = {
  "Ble Sucre": "適合排成十二區甜點早餐站，重點可放在可頌、奶油感重的酥皮點心與外帶甜點；如果早上不想坐太久，買了之後接著去河岸或巴士底周邊散步很順。",
  "BO&MIE Saint Martin": "主打選擇很多的大型麵包甜點櫃，從可頌、法棍三明治到漂亮甜點都容易分食；放在聖馬丁運河附近很實用，適合多人各買一樣交換吃。",
  "BOULANGERIE MODERNE": "適合早上外帶可頌、麵包或三明治作為輕早餐；如果當天行程在附近，抓一站買了邊走邊吃，比坐完整早午餐更有彈性。",
  "Bonjour Jacob": "適合坐下來喝咖啡、吃蛋料理或簡單甜點，讓早上節奏不要太趕；如果排隊長，也可以改成外帶咖啡後接續散步。",
  "Boris Café Pâtisserie": "甜點與咖啡都適合作為上午補給，可留意招牌糕點、塔類或酥皮品項；建議和附近散步一起排，避免為了甜點單獨繞太遠。",
  "Boulangerie Utopie": "適合早上外帶可頌、麵包或三明治作為輕早餐；如果當天行程在附近，抓一站買了邊走邊吃，比坐完整早午餐更有彈性。",
  "Brigat'": "適合當作一天開始的輕食站，先用咖啡、麵包或簡單甜點墊胃；是否久坐可依當天體力和排隊狀況調整。",
  "Carré Pain de Mie": "適合早上外帶可頌、麵包或三明治作為輕早餐；如果當天行程在附近，抓一站買了邊走邊吃，比坐完整早午餐更有彈性。",
  "Cedric Grolet Opéra": "甜點控朝聖點，重點是水果造型甜點、花朵可頌與精緻外觀；價格和排隊都偏高，建議當作歌劇院附近的重點甜點站，不要排在趕時間的空檔。",
  "Du Pain et des Idées": "聖馬丁運河旁經典麵包店，招牌可鎖定 pistachio chocolate escargot、pain des amis 和酥皮類；最適合外帶後到運河邊慢慢吃。",
  "Immersion Vendôme - Everyday Brunch | Lunch | Coffee": "適合坐下來喝咖啡、吃蛋料理或簡單甜點，讓早上節奏不要太趕；如果排隊長，也可以改成外帶咖啡後接續散步。",
  "JUS - Boulangerie / Pâtisserie - végétarienne, engagée et responsable": "適合早上外帶可頌、麵包或三明治作為輕早餐；如果當天行程在附近，抓一站買了邊走邊吃，比坐完整早午餐更有彈性。",
  "La Maison d'Isabelle": "以可頌聞名，適合想吃經典法式奶油香與酥皮層次時安排；靠近拉丁區與塞納河左岸，早上買完後接萬神殿或聖日耳曼路線都方便。",
  "La Pâtisserie Cyril Lignac": "甜點與咖啡都適合作為上午補給，可留意招牌糕點、塔類或酥皮品項；建議和附近散步一起排，避免為了甜點單獨繞太遠。",
  "Laurent Duchêne": "甜點與咖啡都適合作為上午補給，可留意招牌糕點、塔類或酥皮品項；建議和附近散步一起排，避免為了甜點單獨繞太遠。",
  "Le Grenier à Pain Abbesses Bodian": "適合早上外帶可頌、麵包或三明治作為輕早餐；如果當天行程在附近，抓一站買了邊走邊吃，比坐完整早午餐更有彈性。",
  "Les Petits Mitrons": "甜點與咖啡都適合作為上午補給，可留意招牌糕點、塔類或酥皮品項；建議和附近散步一起排，避免為了甜點單獨繞太遠。",
  "Liberté": "適合早上外帶可頌、麵包或三明治作為輕早餐；如果當天行程在附近，抓一站買了邊走邊吃，比坐完整早午餐更有彈性。",
  "Lorette boulangerie pâtisserie": "適合早上外帶可頌、麵包或三明治作為輕早餐；如果當天行程在附近，抓一站買了邊走邊吃，比坐完整早午餐更有彈性。",
  "Mamiche": "人氣很高的巴黎麵包店，甜鹹品項都強，常見亮點是 babka、可頌、布里歐與三明治；適合外帶當早餐，但尖峰常要排隊，行程別排太緊。",
  "Manteigaria": "甜點與咖啡都適合作為上午補給，可留意招牌糕點、塔類或酥皮品項；建議和附近散步一起排，避免為了甜點單獨繞太遠。",
  "Petite Île Boulangerie": "瑪黑區早餐很順路的麵包店，可鎖定可頌、酸種麵包或簡單甜鹹麵包；很適合作為 Merci 周邊散步前的第一站，不必吃太正式。",
  "Philippe Conticini Café Paris Montmartre": "甜點與咖啡都適合作為上午補給，可留意招牌糕點、塔類或酥皮品項；建議和附近散步一起排，避免為了甜點單獨繞太遠。",
  "Stohrer": "老牌甜點店本身很有歷史感，適合在 Rue Montorgueil 散步時順吃；可留意 baba au rhum、閃電泡芙和經典法式糕點。",
  "Tout Autour du Pain": "適合早上外帶可頌、麵包或三明治作為輕早餐；如果當天行程在附近，抓一站買了邊走邊吃，比坐完整早午餐更有彈性。",
  "Abri Soba": "適合想吃拉麵、定食、蕎麥麵或丼飯類熱食時安排；口味相對熟悉，對多人同行也是安全的換口味選項。",
  "Au P'tit Crêpe": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "AU PASSAGE": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Au Pied de Fouet": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Aux Lyonnais": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "BigLove": "適合多人分享披薩、義大利麵、布拉塔或提拉米蘇；通常氣氛比較輕鬆，適合作為逛街後的聚餐選擇。",
  "Blanc": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Bouillon Chartier": "重點是平價傳統法式餐館與熱鬧老派空間，可點洋蔥湯、牛排薯條、油封鴨或布丁類甜點；適合體驗氣氛，不適合期待精緻慢餐。",
  "Brasserie Saigon": "適合想吃河粉、春捲、米線或清爽亞洲熱食時安排；旅行中穿插一餐越式會比連續西餐輕鬆，也比較不拖慢下午行程。",
  "Breizh Café": "主打布列塔尼鹹可麗餅與蘋果酒，適合午餐或不想太重的晚餐；建議多人點不同口味分食，甜可麗餅可作收尾。",
  "Carboni's": "適合多人分享披薩、義大利麵、布拉塔或提拉米蘇；通常氣氛比較輕鬆，適合作為逛街後的聚餐選擇。",
  "Casa San Pablo": "適合放在附近主要行程前後當正餐，先確認營業時間與是否需要訂位；多人同行時可優先選能分享、出餐穩定的菜色。",
  "Chez l'oncle Lin": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "Com Restaurant": "適合想吃河粉、春捲、米線或清爽亞洲熱食時安排；旅行中穿插一餐越式會比連續西餐輕鬆，也比較不拖慢下午行程。",
  "Combo Restaurant - traiteur": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "D Noodles": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "Dandelion": "偏現代法式與創意餐廳路線，適合想吃季節菜、小份菜與較有記憶點的晚餐；位置不在核心觀光軸上，建議有訂位或同區行程再特地前往。",
  "FAUNA": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Folderol": "結合冰淇淋、甜點與自然酒吧氣氛，適合晚餐後來吃甜口再喝一杯；十一區晚上安排它，比白天專程去更自然。",
  "Foodi Jia-Ba-Buay": "適合放在附近主要行程前後當正餐，先確認營業時間與是否需要訂位；多人同行時可優先選能分享、出餐穩定的菜色。",
  "Freddy’s": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "FrenchParadox - Canard & Champagne": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Go Oun": "適合想吃拉麵、定食、蕎麥麵或丼飯類熱食時安排；口味相對熟悉，對多人同行也是安全的換口味選項。",
  "Ha Noi 1988": "適合想吃河粉、春捲、米線或清爽亞洲熱食時安排；旅行中穿插一餐越式會比連續西餐輕鬆，也比較不拖慢下午行程。",
  "Kadoya": "適合想吃拉麵、定食、蕎麥麵或丼飯類熱食時安排；口味相對熟悉，對多人同行也是安全的換口味選項。",
  "KIKÉ - Cuisine Taïwanaise & Street Food - 起家厝": "適合放在附近主要行程前後當正餐，先確認營業時間與是否需要訂位；多人同行時可優先選能分享、出餐穩定的菜色。",
  "Kodawari Ramen (Tsukiji)": "以沉浸式築地市場風格聞名，吃拉麵之外也在吃場景；適合想把日式拉麵排成一個有記憶點的餐，但排隊彈性要抓。",
  "L'Office": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "La Banquette Marais": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "La Brigade - Réaumur - Restaurant Paris": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "La Source": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "La Taverne de Zhao": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "La Taverne de Zhao_saint germain des prés": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "Le Bistrot du Peintre": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Le Mabillon - Paris": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Le Petit Bal Perdu": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Le Petit Bouillon Pharamond": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Le Sanglier Bleu": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Les Cocottes": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Les enfants du marché": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Les Fauves Restaurant": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Linette": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Mala Town": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "Marché alimentaire Bastille": "適合放在附近主要行程前後當正餐，先確認營業時間與是否需要訂位；多人同行時可優先選能分享、出餐穩定的菜色。",
  "Mokonuts": "適合放在附近主要行程前後當正餐，先確認營業時間與是否需要訂位；多人同行時可優先選能分享、出餐穩定的菜色。",
  "Mắm From Hanoï": "適合想吃河粉、春捲、米線或清爽亞洲熱食時安排；旅行中穿插一餐越式會比連續西餐輕鬆，也比較不拖慢下午行程。",
  "Ober Mamma": "適合多人分享披薩、義大利麵、布拉塔或提拉米蘇；通常氣氛比較輕鬆，適合作為逛街後的聚餐選擇。",
  "Pedzouille La Grange": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "Pho Bom": "適合想吃河粉、春捲、米線或清爽亞洲熱食時安排；旅行中穿插一餐越式會比連續西餐輕鬆，也比較不拖慢下午行程。",
  "Phở Bánh Cuốn 14 (PHO 14 Opéra)": "歌劇院附近實用越式餐，重點可放在河粉、越式蒸卷與春捲；很適合作為皮諾美術館和小皇宮之間的午餐，速度也比正式餐廳穩。",
  "Pink Mamma": "Big Mamma 系列中很有場景感的一家，適合蒙馬特午餐或晚餐；可點義大利麵、披薩、肉排與提拉米蘇，座位熱門一定要留訂位或排隊彈性。",
  "Pizzeria Popolare": "適合多人分享披薩、義大利麵、布拉塔或提拉米蘇；通常氣氛比較輕鬆，適合作為逛街後的聚餐選擇。",
  "RECTO VERSO": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "RESTAURANT ERH": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "ROJO": "適合放在附近主要行程前後當正餐，先確認營業時間與是否需要訂位；多人同行時可優先選能分享、出餐穩定的菜色。",
  "Septime": "巴黎知名現代法式餐廳，適合把它當成美食行程亮點；重點是季節套餐與酒水搭配，訂位難度高，不適合臨時起意。",
  "Sevenly Heart": "偏韓系甜點與咖啡休息點，適合在瑪黑區逛街中途坐下吃甜點、喝飲料或簡單補充糖分；比較像下午茶／咖啡站，不適合作為正式午晚餐。",
  "Substance": "適合安排成一頓完整正餐，可留意當日主菜、牛排薯條、油封鴨或經典甜點；建議預留比亞洲餐更長的用餐時間。",
  "The Crying Tiger": "適合想吃酸辣、咖哩、炒河粉或烤肉類料理時安排；在巴黎行程中穿插泰式，能讓口味變得更清爽活潑。",
  "Tiger": "聖日耳曼一帶的酒吧與小食選項，適合晚餐後喝一杯或補幾道小點；如果當天左岸散步到晚上，可以當成自然續攤。",
  "Trois Fois Plus de Piment": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "Épicerie primeur Terroirs d'Avenir": "適合放在附近主要行程前後當正餐，先確認營業時間與是否需要訂位；多人同行時可優先選能分享、出餐穩定的菜色。",
  "兩個風車咖啡館": "重點是蒙馬特咖啡館氛圍與《艾蜜莉的異想世界》場景感，可點咖啡、簡餐或甜點短暫停留；更適合作為散步中的咖啡休息，不是正式晚餐主力。",
  "娣小面": "適合想吃麵飯、辣味小菜或熟悉中式熱食時安排；如果連日法式餐廳吃到疲乏，這類餐點很適合回血。",
  "舒芙蕾甜點店": "主軸是現烤舒芙蕾與甜點儀式感，適合當作一區散步中的下午茶；因舒芙蕾通常需要等待，建議不要排在趕下一個預約前。",
  "貝蒂雍": "聖路易島經典冰淇淋店，適合和西堤島、巴黎聖母院周邊或瑪黑散步排在一起；可選雪酪、水果口味或濃郁奶香口味。",
  "팔도_PALDO": "韓式料理適合多人晚餐，能用烤肉、鍋物、煎餅或拌飯類把氣氛做起來；安排在 19:00 後很合理，建議事先訂位。",
  "Boot Café": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Café Kitsuné Vertbois": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Café Verlet": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Carette": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Cortado": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Dreamin' Man": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "I.O Café": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Les Deux Magots": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Maison Nespresso - Le Café": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Noir": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Residence Kann": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Saint Pearl Saint-Germain": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Simple Coffee": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Substance Café": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Terres de Café Daguerre": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "The Beans on Fire - Au Théâtre": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Télescope Café": "適合在景點與景點之間補一杯 espresso、拿鐵或手沖，順便坐下整理行程；建議當成短暫休息站，不要為了它壓縮主景點時間。",
  "Amorino": "適合逛街途中買茶飲、奶茶或冰品補水解膩；停留成本低，最適合炎熱午後或正餐後順手安排。",
  "Fei tea": "適合逛街途中買茶飲、奶茶或冰品補水解膩；停留成本低，最適合炎熱午後或正餐後順手安排。",
  "Laïzé Marais": "適合逛街途中買茶飲、奶茶或冰品補水解膩；停留成本低，最適合炎熱午後或正餐後順手安排。",
  "Laïzé Palais Royal": "適合逛街途中買茶飲、奶茶或冰品補水解膩；停留成本低，最適合炎熱午後或正餐後順手安排。",
  "TeaYammi": "適合逛街途中買茶飲、奶茶或冰品補水解膩；停留成本低，最適合炎熱午後或正餐後順手安排。",
  "228 Litres": "適合晚餐後小酌一杯，依氣氛選調酒、葡萄酒或簡單小食；建議排在同區行程收尾，不要白天特地繞路。",
  "Bar À Bulles": "適合晚餐後小酌一杯，依氣氛選調酒、葡萄酒或簡單小食；建議排在同區行程收尾，不要白天特地繞路。",
  "Le Mary Celeste": "瑪黑區人氣酒吧，重點是調酒、葡萄酒、海鮮小食與輕鬆聊天氣氛；適合正餐後來續攤，也適合多人分享幾道小盤。",
  "Le Victory": "適合晚餐後小酌一杯，依氣氛選調酒、葡萄酒或簡單小食；建議排在同區行程收尾，不要白天特地繞路。",
  "Restaurant Chez Bartolo": "聖日耳曼一帶的義式餐館，適合想吃披薩、義大利麵或經典義式家常菜時安排；比酒吧更適合作為左岸行程後的正式午晚餐。",
  "Terra bar à vins": "適合晚餐後小酌一杯，依氣氛選調酒、葡萄酒或簡單小食；建議排在同區行程收尾，不要白天特地繞路。",
  "Bourse de Commerce - Pinault Collection": "當代藝術與圓形建築空間是亮點，展覽節奏比大型博物館更集中；很適合安排半天室內主景點，並和皇家宮殿、一區午餐串在一起。",
  "Place de la Concorde": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "Place du Trocadero": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "傷兵院": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "國璽公園": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "奧賽博物館": "印象派與後印象派是核心亮點，五樓展區和車站改建空間都值得看；建議先抓莫內、雷諾瓦、梵谷等重點，再視體力補其他樓層。",
  "孚日廣場": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "小皇宮": "常設展免費，建築、中庭花園與館藏都比想像中好看；很適合在香榭大道或協和廣場周邊穿插，雨天也實用。",
  "尼爾森曼德拉花園": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "巴黎凱旋門": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "巴黎古監獄": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "巴黎大皇宮": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "巴黎植物園": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "建築與遺產城": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "快樂文化馬真塔38飯店": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "愛牆": "蒙馬特經典拍照點，停留時間不用長，但很適合作為 Abbesses 到聖心堂路線的開場；人多時拍照節奏要快。",
  "戰神廣場": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "杜樂麗花園": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "法國國家圖書館 黎塞留館": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "海軍府": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "瘋馬秀": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "皇家宮殿花園": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "盧森堡公園": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "羅浮宮": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "聖徒禮拜堂": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "聖心堂": "蒙馬特高地代表地標，教堂內部和前方巴黎市景都值得留時間；日落前後最有氣氛，但階梯與人潮都要預留體力。",
  "聖猶士坦堂": "適合和同區景點串成步行路線，停留時間可依天氣與體力調整；如果是室內點，雨天或高溫時也能當作很好用的備案。",
  "Arket": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "Essential Parfums": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "Fleux": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "LEMAIRE | Elzévir": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "Léclaireur": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "Maison": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "Merci": "瑪黑區代表選物店，生活雜貨、服飾、書與設計小物都好逛；很適合排在 Petite Île 早餐後，作為 8/14 早上重點。",
  "Officine Universelle Buly 1803": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "Shop Cabinet Bébé - Paris 02": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "Supreme Paris": "適合排進同區逛街路線，慢慢看服飾、香氛、生活選物或百貨櫃位；如果沒有明確購物需求，當作順路短停即可。",
  "拉法葉百貨 巴黎奧斯曼旗艦店": "適合集中購物、退稅與看品牌櫃位，彩繪穹頂和頂樓景觀也值得停留；人潮多，建議有明確購物清單再深入逛。",
  "樂蓬馬歇百貨公司": "左岸高級百貨氣氛比右岸觀光百貨從容，適合看設計品牌、美妝與食品館；很適合和聖日耳曼或六七區行程搭配。",
  "莎瑪麗丹百貨公司": "翻新後建築本身很有看點，適合和羅浮宮、塞納河右岸或 Pont Neuf 一起排；購物之外也可以當成建築參觀點。",
  "Trattoria Mirta": "偏在地 trattoria 氣氛，適合想吃米蘭家常菜、手工義大利麵與季節主菜的一餐；位置在 Casoretto 一帶，較適合專程安排晚餐，不是市中心順路快閃。",
  "Ristorante Ratanà": "主打現代米蘭與倫巴底料理，適合想吃 risotto alla milanese、ossobuco 或季節菜的精緻午餐；Porta Nuova 周邊行程很順，建議訂位。",
  "miscusi | pasta fresca - Milano Cadorna": "主打新鮮義大利麵與可自選醬料，適合想快速吃一餐 pasta 又不想太正式時安排；Cadorna 位置很方便，適合轉車或市中心移動中補餐。",
  "Langosteria": "米蘭高級海鮮餐廳代表，適合想吃生食海鮮、龍蝦、海鮮義大利麵與較有儀式感晚餐；價格偏高，建議當作美食亮點而非臨時備案。",
  "Pizzium - Via Anfossi": "主打拿坡里風格披薩與各地區特色口味，適合想吃輕鬆披薩晚餐；Via Anfossi 位置較偏 Porta Vittoria，適合同區行程或搭車前往。",
  "Obicà Mozzarella Bar - Cusani": "以水牛 mozzarella、火腿、披薩與義式小食為主，適合多人分享；Cusani 靠近 Brera 與 Castello，市中心散步後安排很方便。",
  "Spontini": "米蘭經典厚片披薩品牌，招牌是高而鬆軟、起司感強的 pizza al trancio；適合快速補餐或外帶，不需要排成正式餐廳。",
  "Trattoria Madonnina": "Navigli 一帶老派 trattoria 氛圍，適合想吃燉飯、肉類主菜與傳統米蘭餐的晚上；搭配運河散步很自然，建議尖峰時段先訂位。",
  "Ristorante Nuova Arena": "靠近 Arena／Brera 一帶的義式餐館，適合在市中心北側行程後吃一頓穩定正餐；可把它當作 Brera、Sempione 周邊的晚餐備案。",
  "La Gioia San Marco": "San Marco 一帶的義式餐廳，適合想吃海鮮、義大利麵或較精緻的義式正餐；靠近 Brera，晚上散步後銜接方便。",
  "Al Baretto San Marco": "經典米蘭餐館感較強，適合想吃傳統義式主菜、risotto 或商務餐廳氛圍的一餐；San Marco 位置適合 Brera 周邊晚餐。",
  "Gloria Osteria Milano": "Big Mamma 系列的熱鬧義式餐廳，適合多人分享披薩、義大利麵、起司與甜點；氣氛比傳統 trattoria 更活潑，熱門時段要留意訂位。",
  "La Latteria": "Brera 一帶小巧在地餐館，適合想吃簡單但有溫度的家常義式料理；座位不多，適合兩人或小團體，不適合趕時間。",
  "Sugo Milano - Duomo": "Duomo 周邊的 pasta 選項，適合市中心行程中快速吃義大利麵；位置方便勝過目的性，適合大教堂、拱廊附近的午晚餐。",
  "Trattoria Trippa": "米蘭人氣現代 trattoria，以內臟料理、季節小菜與手工 pasta 聞名；訂位難度較高，適合把它當成 Porta Romana 一帶的美食重點。",
  "Trattoria Bolognese da Mauro": "偏 Bologna 家常菜與傳統 pasta 路線，適合想吃 tagliatelle、ragù 或樸實義式主菜；位置在 Navigli 西側，建議搭配同區行程。",
  "Nebbia": "Navigli 周邊的現代餐廳，適合想吃季節菜、小盤分享與自然酒感的一餐；比傳統 trattoria 更輕盈，適合晚餐慢慢吃。",
  "Dal Bolognese Milano": "主打 Bologna 風味與經典義式餐館氣氛，適合想吃手工 pasta、肉醬、傳統主菜的一餐；位置靠近市中心南側，適合安排正式晚餐。",
  "Flash": "Duomo 東南側的義式餐館選項，適合市中心行程中找一餐簡單 pasta、披薩或主菜；可作為大教堂附近不想走遠時的備案。",
  "NYX Hotel Milan": "米蘭住宿基地，靠近 Milano Centrale，適合搭 Malpensa Express、前往湖區或跨城火車；周邊以交通便利為主，晚間回飯店也相對省力。",
  "Terrazza Duomo 21": "大教堂旁的景觀酒吧／餐廳，重點是露台視角與 Duomo 廣場氛圍；適合喝一杯、拍照與休息，餐飲本身不必當成主目的。",
  "米蘭主教座堂": "米蘭最重要地標，外觀、內部與屋頂都值得安排；若時間有限，屋頂視角最有記憶點，建議事先買含電梯票。",
  "星巴克臻選® 米蘭烘焙工坊": "歐洲第一家 Starbucks Reserve Roastery，空間、烘焙設備與吧台體驗是重點；適合當成市中心咖啡休息與參觀點。",
  "Maccheroni - La Carbonara N°1 di Milano": "主打羅馬風格 carbonara 與義大利麵，適合想吃濃郁蛋黃、起司與 guanciale 風味時安排；份量感明確，適合作為 Brera 午餐。"
};
const DISTRICT_LOOKUP = {
  "228 Litres": "18區",
  "AU PASSAGE": "11區",
  "Abri Soba": "9區",
  "Amorino": "14區",
  "Arket": "4區",
  "Au P'tit Crêpe": "1區",
  "Au Pied de Fouet": "7區",
  "Aux Lyonnais": "2區",
  "BO&MIE Saint Martin": "3區",
  "BOULANGERIE MODERNE": "5區",
  "Bar À Bulles": "18區",
  "BigLove": "3區",
  "Blanc": "10區",
  "Ble Sucre": "12區",
  "Bonjour Jacob": "6區",
  "Boot Café": "3區",
  "Boris Café Pâtisserie": "18區",
  "Bouillon Chartier": "9區",
  "Boulangerie Utopie": "11區",
  "Bourse de Commerce - Pinault Collection": "1區",
  "Brasserie Saigon": "14區",
  "Breizh Café": "6區",
  "Brigat'": "3區",
  "Café Kitsuné Vertbois": "3區",
  "Café Verlet": "1區",
  "Carboni's": "3區",
  "Carette": "16區",
  "Carré Pain de Mie": "4區",
  "Casa San Pablo": "4區",
  "Cedric Grolet Opéra": "2區",
  "Chez l'oncle Lin": "5區",
  "Com Restaurant": "1區",
  "Combo Restaurant - traiteur": "6區",
  "Cortado": "3區",
  "D Noodles": "11區",
  "Dandelion": "20區",
  "Dreamin' Man": "11區",
  "Du Pain et des Idées": "10區",
  "Essential Parfums": "6區",
  "FAUNA": "11區",
  "Fei tea": "4區",
  "Fleux": "4區",
  "Folderol": "11區",
  "Foodi Jia-Ba-Buay": "2區",
  "Freddy’s": "2區",
  "FrenchParadox - Canard & Champagne": "2區",
  "Go Oun": "1區",
  "Ha Noi 1988": "4區",
  "I.O Café": "3區",
  "Immersion Vendôme - Everyday Brunch | Lunch | Coffee": "1區",
  "JUS - Boulangerie / Pâtisserie - végétarienne, engagée et responsable": "18區",
  "KIKÉ - Cuisine Taïwanaise & Street Food - 起家厝": "3區",
  "Kadoya": "1區",
  "Kodawari Ramen (Tsukiji)": "1區",
  "L'Office": "9區",
  "LEMAIRE | Elzévir": "3區",
  "La Banquette Marais": "3區",
  "La Brigade - Réaumur - Restaurant Paris": "2區",
  "La Maison d'Isabelle": "5區",
  "La Pâtisserie Cyril Lignac": "9區",
  "La Source": "7區",
  "La Taverne de Zhao": "2區",
  "La Taverne de Zhao_saint germain des prés": "6區",
  "Laurent Duchêne": "13區",
  "Laïzé Marais": "3區",
  "Laïzé Palais Royal": "1區",
  "Le Bistrot du Peintre": "12區",
  "Le Grenier à Pain Abbesses Bodian": "18區",
  "Le Mabillon - Paris": "6區",
  "Le Mary Celeste": "3區",
  "Le Petit Bal Perdu": "5區",
  "Le Petit Bouillon Pharamond": "1區",
  "Le Sanglier Bleu": "18區",
  "Le Victory": "8區",
  "Les Cocottes": "7區",
  "Les Deux Magots": "6區",
  "Les Fauves Restaurant": "14區",
  "Les Petits Mitrons": "18區",
  "Les enfants du marché": "3區",
  "Liberté": "17區",
  "Linette": "7區",
  "Lorette boulangerie pâtisserie": "15區",
  "Léclaireur": "3區",
  "Maison": "13區",
  "Maison Nespresso - Le Café": "4區",
  "Mala Town": "3區",
  "Mamiche": "9區",
  "Manteigaria": "8區",
  "Marché alimentaire Bastille": "11區",
  "Merci": "3區",
  "Mokonuts": "11區",
  "Mắm From Hanoï": "2區",
  "Noir": "4區",
  "Ober Mamma": "11區",
  "Officine Universelle Buly 1803": "3區",
  "Pedzouille La Grange": "15區",
  "Petite Île Boulangerie": "3區",
  "Philippe Conticini Café Paris Montmartre": "18區",
  "Pho Bom": "13區",
  "Phở Bánh Cuốn 14 (PHO 14 Opéra)": "1區",
  "Pink Mamma": "9區",
  "Pizzeria Popolare": "2區",
  "Place de la Concorde": "8區",
  "Place du Trocadero": "16區",
  "RECTO VERSO": "3區",
  "RESTAURANT ERH": "2區",
  "ROJO": "3區",
  "Residence Kann": "11區",
  "Restaurant Chez Bartolo": "6區",
  "Saint Pearl Saint-Germain": "7區",
  "Septime": "11區",
  "Sevenly Heart": "3區",
  "Shop Cabinet Bébé - Paris 02": "2區",
  "Simple Coffee": "18區",
  "Stohrer": "2區",
  "Substance": "16區",
  "Substance Café": "2區",
  "Supreme Paris": "3區",
  "TeaYammi": "1區",
  "Terra bar à vins": "3區",
  "Terres de Café Daguerre": "14區",
  "The Beans on Fire - Au Théâtre": "10區",
  "The Crying Tiger": "6區",
  "Tiger": "6區",
  "Tout Autour du Pain": "3區",
  "Trois Fois Plus de Piment": "14區",
  "Télescope Café": "1區",
  "Épicerie primeur Terroirs d'Avenir": "2區",
  "傷兵院": "7區",
  "兩個風車咖啡館": "18區",
  "國璽公園": "1區",
  "奧賽博物館": "7區",
  "娣小面": "3區",
  "孚日廣場": "4區",
  "小皇宮": "8區",
  "尼爾森曼德拉花園": "1區",
  "巴黎凱旋門": "8區",
  "巴黎古監獄": "1區",
  "巴黎大皇宮": "8區",
  "巴黎植物園": "5區",
  "建築與遺產城": "16區",
  "快樂文化馬真塔38飯店": "10區",
  "愛牆": "18區",
  "戰神廣場": "7區",
  "拉法葉百貨 巴黎奧斯曼旗艦店": "9區",
  "杜樂麗花園": "1區",
  "樂蓬馬歇百貨公司": "7區",
  "法國國家圖書館 黎塞留館": "2區",
  "海軍府": "8區",
  "瘋馬秀": "8區",
  "皇家宮殿花園": "1區",
  "盧森堡公園": "6區",
  "羅浮宮": "1區",
  "聖徒禮拜堂": "1區",
  "聖心堂": "18區",
  "聖猶士坦堂": "1區",
  "舒芙蕾甜點店": "1區",
  "莎瑪麗丹百貨公司": "1區",
  "貝蒂雍": "4區",
  "팔도_PALDO": "5區",
  "Trattoria Mirta": "Casoretto",
  "Ristorante Ratanà": "Porta Nuova",
  "miscusi | pasta fresca - Milano Cadorna": "Cadorna",
  "Langosteria": "Navigli",
  "Pizzium - Via Anfossi": "Porta Vittoria",
  "Obicà Mozzarella Bar - Cusani": "Brera",
  "Spontini": "Duomo",
  "Trattoria Madonnina": "Navigli",
  "Ristorante Nuova Arena": "Arena",
  "La Gioia San Marco": "Brera",
  "Al Baretto San Marco": "Brera",
  "Gloria Osteria Milano": "Brera",
  "La Latteria": "Brera",
  "Sugo Milano - Duomo": "Duomo",
  "Trattoria Trippa": "Porta Romana",
  "Trattoria Bolognese da Mauro": "Navigli",
  "Nebbia": "Navigli",
  "Dal Bolognese Milano": "Missori",
  "Flash": "Duomo",
  "NYX Hotel Milan": "Centrale",
  "Terrazza Duomo 21": "Duomo",
  "米蘭主教座堂": "Duomo",
  "星巴克臻選® 米蘭烘焙工坊": "Cordusio",
  "Maccheroni - La Carbonara N°1 di Milano": "Brera"
};

const CITY_LOOKUP = {
  "Trattoria Mirta": "米蘭",
  "Ristorante Ratanà": "米蘭",
  "miscusi | pasta fresca - Milano Cadorna": "米蘭",
  "Langosteria": "米蘭",
  "Pizzium - Via Anfossi": "米蘭",
  "Obicà Mozzarella Bar - Cusani": "米蘭",
  "Spontini": "米蘭",
  "Trattoria Madonnina": "米蘭",
  "Ristorante Nuova Arena": "米蘭",
  "La Gioia San Marco": "米蘭",
  "Al Baretto San Marco": "米蘭",
  "Gloria Osteria Milano": "米蘭",
  "La Latteria": "米蘭",
  "Sugo Milano - Duomo": "米蘭",
  "Trattoria Trippa": "米蘭",
  "Trattoria Bolognese da Mauro": "米蘭",
  "Nebbia": "米蘭",
  "Dal Bolognese Milano": "米蘭",
  "Flash": "米蘭",
  "NYX Hotel Milan": "米蘭",
  "Terrazza Duomo 21": "米蘭",
  "米蘭主教座堂": "米蘭",
  "星巴克臻選® 米蘭烘焙工坊": "米蘭",
  "Maccheroni - La Carbonara N°1 di Milano": "米蘭"
};

const CITY_ORDER = ["巴黎", "米蘭"];

const ITINERARY_STOPS = {
  "8/9（日）抵達米蘭｜大教堂與市中心": [
    ["NYX Hotel Milan", "NYX Hotel Milan, Milan"],
    ["Brera", "Brera, Milan"],
    ["Maccheroni", "Maccheroni La Carbonara N°1 di Milano"],
    ["米蘭大教堂", "Duomo di Milano"],
    ["Navigli", "Navigli, Milan"]
  ],
  "8/10（一）科莫湖一日遊｜Como＋Bellagio＋Varenna": [
    ["Como", "Como, Italy"],
    ["Bellagio", "Bellagio, Lake Como"],
    ["Varenna", "Varenna, Italy"],
    ["Osteria Serafina", "Osteria Serafina Milano"]
  ],
  "8/11（二）維洛納一日遊": [
    ["Verona Arena", "Verona Arena"],
    ["茱麗葉之家", "Casa di Giulietta Verona"],
    ["Ponte Pietra", "Ponte Pietra Verona"],
    ["Castel San Pietro", "Castel San Pietro Verona"]
  ],
  "8/12（三）米蘭新城區｜搭車前往巴黎": [
    ["BAM", "Biblioteca degli Alberi Milano"],
    ["Ratanà", "Ristorante Ratanà Milano"],
    ["Paris Gare de Lyon", "Paris Gare de Lyon"],
    ["Hôtel Magenta 38", "Hôtel Magenta 38 Paris"]
  ],
  "8/13（四）飯店周邊早餐｜聖馬丁運河｜蒙馬特｜Pink Mamma｜聖心堂日落": [
    ["Mamiche", "Mamiche Paris"],
    ["Liberté", "Liberté Paris"],
    ["Du Pain et des Idées", "Du Pain et des Idées Paris"],
    ["聖馬丁運河", "Canal Saint-Martin Paris"],
    ["Pink Mamma", "Pink Mamma Paris"],
    ["愛牆", "Le Mur des Je t'aime Paris"],
    ["聖心堂", "Sacré-Cœur Paris"]
  ],
  "8/14（五）瑪黑區早餐｜Merci 周邊｜皮諾美術館｜PHO 14 Opéra｜小皇宮｜팔도_PALDO": [
    ["Petite Île", "Petite Île Boulangerie Paris"],
    ["Merci", "Merci 111 Boulevard Beaumarchais Paris"],
    ["皮諾美術館", "Bourse de Commerce Pinault Collection Paris"],
    ["PHO 14 Opéra", "Phở Bánh Cuốn 14 Opéra Paris"],
    ["小皇宮", "Petit Palais Paris"],
    ["팔도_PALDO", "팔도_PALDO Paris"]
  ],
  "8/15（六，法國國定假日）瑪黑區｜街區散步與彈性購物": [
    ["Breizh Café", "Breizh Café Paris"],
    ["Place des Vosges", "Place des Vosges Paris"],
    ["Village Saint-Paul", "Village Saint-Paul Paris"],
    ["Rue des Rosiers", "Rue des Rosiers Paris"],
    ["Cortado", "Cortado Paris"],
    ["Freddy’s", "Freddy’s Paris"]
  ],
  "8/16（日）FAUNA｜奧塞博物館｜巴黎鐵塔景觀": [
    ["FAUNA", "FAUNA Paris"],
    ["奧塞博物館", "Musée d'Orsay Paris"],
    ["Champ de Mars", "Champ de Mars Paris"],
    ["Trocadéro", "Trocadéro Paris"],
    ["艾菲爾鐵塔", "Eiffel Tower Paris"]
  ],
  "8/17（一）巴黎軍事博物館｜塞納河遊船": [
    ["巴黎軍事博物館", "Musée de l'Armée Paris"],
    ["Rue Cler", "Rue Cler Paris"],
    ["Bateaux Parisiens", "Bateaux Parisiens Eiffel Tower"]
  ],
  "8/18（二）巴黎返台": [
    ["Hôtel Magenta 38", "Hôtel Magenta 38 Paris"],
    ["CDG Terminal 1", "Charles de Gaulle Airport Terminal 1"]
  ]
};

const ITINERARY_GUIDE = {
  "8/8（六）台灣出發": {
    headline: "晚間班機出發，隔夜飛往米蘭",
    overview: ["23:55 搭乘 BR95 自桃園機場出發。"],
    notes: ["起飛前先完成線上報到，隨身行李放入第一天會直接用到的盥洗用品與換洗衣物。"],
    links: [["桃園機場", "Taoyuan International Airport"]]
  },
  "8/9（日）抵達米蘭｜大教堂與市中心": {
    headline: "Brera 午餐後進市中心，傍晚進米蘭大教堂，晚上散步 Navigli",
    overview: [
      "07:35 抵達 Malpensa 機場，完成入境與領行李。",
      "09:00–10:00 搭 Malpensa Express 到 Milano Centrale，寄放行李後前往 Brera。",
      "11:15–12:45 在 Brera 街區散步，12:45 於 Maccheroni 午餐。",
      "14:00–15:30 依序參觀 Starbucks Reserve Roastery Milano、Terrazza Duomo 21 與艾曼紐二世拱廊。",
      "16:30–18:30 進米蘭大教堂與屋頂。",
      "18:30–21:30 前往 Porta Genova、Darsena、Naviglio Grande、Vicolo dei Lavandai，運河區晚餐收尾。"
    ],
    notes: [
      "16:30 大教堂票券與晚間 Navigli 優先保留；若早上延誤，先縮短 Brera。",
      "大教堂票券需含屋頂電梯，建議提前 15–20 分鐘到集合點。",
      "若體力下降，可在 Navigli 看完日落後提早回飯店。"
    ],
    links: [
      ["Malpensa 機場", "Milan Malpensa Airport"],
      ["Malpensa Express", "Malpensa Express Milano Centrale"],
      ["Milano Centrale", "Milano Centrale"],
      ["Brera", "Brera Milan"],
      ["Maccheroni", "Maccheroni La Carbonara N°1 di Milano"],
      ["Starbucks Reserve Roastery Milano", "Starbucks Reserve Roastery Milano"],
      ["Terrazza Duomo 21", "Terrazza Duomo 21 Milan"],
      ["艾曼紐二世拱廊", "Galleria Vittorio Emanuele II Milan"],
      ["米蘭大教堂", "Duomo di Milano"],
      ["Porta Genova", "Porta Genova Milan"],
      ["Darsena", "Darsena Milan"],
      ["Naviglio Grande", "Naviglio Grande Milan"],
      ["Vicolo dei Lavandai", "Vicolo dei Lavandai Milan"]
    ]
  },
  "8/10（一）科莫湖一日遊｜Como＋Bellagio＋Varenna": {
    headline: "早上進科莫湖，依序走 Como、Bellagio、Varenna，晚上回米蘭吃 Osteria Serafina",
    overview: [
      "07:10–07:50 在 Milano Centrale 買 Spontini Pizza，之後搭車前往 Como San Giovanni。",
      "09:35–10:10 先走 Como 老城與 Como Cathedral 外圍。",
      "10:30–12:04 搭船前往 Bellagio，中午在 Bellagio 散步與午餐。",
      "14:25–14:40 再搭船到 Varenna，走 Passeggiata degli Innamorati 與湖畔老街。",
      "17:35–18:40 從 Varenna-Esino 搭車回 Milano Centrale。",
      "20:15 在 Osteria Serafina 晚餐。"
    ],
    notes: [
      "船班與火車班次出發前一週再確認，Como 碼頭旺季排隊時間要抓寬鬆。",
      "若錯過 Como 開出的主航班，優先保住 Bellagio 與 Varenna，不硬塞額外景點。",
      "若遇雷雨或渡輪大幅異常，建議直接改成米蘭室內備案。"
    ],
    links: [
      ["Milano Centrale", "Milano Centrale"],
      ["Spontini Pizza", "Spontini Milano Centrale"],
      ["Como San Giovanni", "Como San Giovanni"],
      ["Como", "Como Italy"],
      ["Como Cathedral", "Como Cathedral"],
      ["Bellagio", "Bellagio Lake Como"],
      ["Varenna", "Varenna Italy"],
      ["Passeggiata degli Innamorati", "Passeggiata degli Innamorati Varenna"],
      ["Varenna-Esino", "Varenna-Esino"],
      ["Osteria Serafina", "Osteria Serafina Milano"]
    ]
  },
  "8/11（二）維洛納一日遊": {
    headline: "中午到維洛納，主攻競技場、茱麗葉之家與河岸觀景",
    overview: [
      "09:00 從 NYX Hotel Milan 出發，搭高鐵前往 Verona Porta Nuova。",
      "11:20–12:20 先看 Verona Arena 與 Piazza Bra。",
      "12:45–14:00 在 Piazza delle Erbe 周邊午餐。",
      "14:15–15:10 進 Casa di Giulietta 完整參觀。",
      "15:10–17:35 續走 Piazza dei Signori、Arche Scaligere、Ponte Pietra，最後搭纜車上 Castel San Pietro。",
      "19:00 後搭高鐵回米蘭。"
    ],
    notes: [
      "茱麗葉之家需事先預約指定時段，持 Verona Card 也一樣要先預約。",
      "若高溫明顯，車站到老城先搭公車或計程車，不建議一開始就步行長段。",
      "競技場若因歌劇搭台限制開放，照原路線保留外觀與廣場即可。"
    ],
    links: [
      ["NYX Hotel Milan", "NYX Hotel Milan"],
      ["Verona Porta Nuova", "Verona Porta Nuova"],
      ["Verona Arena", "Verona Arena"],
      ["Piazza Bra", "Piazza Bra Verona"],
      ["Piazza delle Erbe", "Piazza delle Erbe Verona"],
      ["Casa di Giulietta", "Casa di Giulietta Verona"],
      ["Piazza dei Signori", "Piazza dei Signori Verona"],
      ["Arche Scaligere", "Arche Scaligere Verona"],
      ["Ponte Pietra", "Ponte Pietra Verona"],
      ["Castel San Pietro", "Castel San Pietro Verona"]
    ]
  },
  "8/12（三）米蘭新城區｜搭車前往巴黎": {
    headline: "上午輕鬆走 Porta Nuova 與 BAM，中午吃 Ratanà，下午搭車前往巴黎",
    overview: [
      "08:30–10:00 早餐、退房，將行李寄放在 NYX Hotel Milan。",
      "10:05–11:45 走 Piazza Gae Aulenti、BAM 與 Bosco Verticale 外觀。",
      "12:00–13:30 在 Ristorante Ratanà 午餐。",
      "13:45–15:20 回 NYX Hotel Milan 取行李，前往 Milano Centrale 候車。",
      "15:53 搭 Trenitalia France 9296，22:36 抵達 Paris Gare de Lyon。",
      "抵達後搭車前往 Hôtel Magenta 38 辦理入住。"
    ],
    notes: [
      "Ratanà 需先確認 8/12 是否營業，並註明 13:30 前需離席。",
      "9296 出發前再看一次是否有工程、罷工或月台變更通知。",
      "巴黎段抵達時間較晚，建議直接搭計程車到飯店。"
    ],
    links: [
      ["NYX Hotel Milan", "NYX Hotel Milan"],
      ["Piazza Gae Aulenti", "Piazza Gae Aulenti Milan"],
      ["BAM", "Biblioteca degli Alberi Milano"],
      ["Bosco Verticale", "Bosco Verticale Milan"],
      ["Ristorante Ratanà", "Ristorante Ratanà Milano"],
      ["Milano Centrale", "Milano Centrale"],
      ["Paris Gare de Lyon", "Paris Gare de Lyon"],
      ["Hôtel Magenta 38", "Hotel Magenta 38 Paris"]
    ]
  },
  "8/13（四）飯店周邊早餐｜聖馬丁運河｜蒙馬特｜Pink Mamma｜聖心堂日落": {
    headline: "早餐散步後進蒙馬特，午餐 Pink Mamma，傍晚在聖心堂看日落",
    overview: [
      "08:30–09:30 在 Mamiche、Liberté 或 Du Pain et des Idées 擇一吃早餐。",
      "09:30–10:15 走聖馬丁運河，之後慢慢移動往蒙馬特。",
      "12:00–12:50 先看 Abbesses 一帶與愛牆。",
      "13:00–14:30 在 Pink Mamma 午餐。",
      "14:30–17:30 續走 Rue des Abbesses、Rue de l’Abreuvoir、La Maison Rose、Place du Tertre。",
      "17:30–20:30 進聖心堂並保留高地看日落前後景色。"
    ],
    notes: [
      "早餐店不先鎖死，當天依排隊情況決定即可。",
      "Pink Mamma 建議預約，午餐尖峰不適合臨時排隊。",
      "若想省體力，可用 Montmartre funicular 取代聖心堂前長階梯。"
    ],
    links: [
      ["Mamiche", "Mamiche Paris"],
      ["Liberté", "Liberté Paris"],
      ["Du Pain et des Idées", "Du Pain et des Idées Paris"],
      ["聖馬丁運河", "Canal Saint-Martin Paris"],
      ["Abbesses", "Abbesses Paris"],
      ["愛牆", "Le Mur des Je t'aime Paris"],
      ["Pink Mamma", "Pink Mamma Paris"],
      ["Rue des Abbesses", "Rue des Abbesses Paris"],
      ["Rue de l’Abreuvoir", "Rue de l'Abreuvoir Paris"],
      ["La Maison Rose", "La Maison Rose Paris"],
      ["Place du Tertre", "Place du Tertre Paris"],
      ["聖心堂", "Sacré-Cœur Paris"],
      ["Montmartre funicular", "Funiculaire de Montmartre"]
    ]
  },
  "8/14（五）瑪黑區早餐｜Merci 周邊｜皮諾美術館｜PHO 14 Opéra｜小皇宮｜팔도_PALDO": {
    headline: "早餐後先走瑪黑區，之後看皮諾美術館與小皇宮，晚上吃 PALDO",
    overview: [
      "09:30–10:15 在 Petite Île Boulangerie 早餐。",
      "10:15–11:00 走 Merci 周邊街區。",
      "11:20–13:00 參觀 Bourse de Commerce – Pinault Collection。",
      "13:15–14:15 在 Phở Bánh Cuốn 14 Opéra 午餐。",
      "15:00–17:15 參觀 Petit Palais。",
      "19:00 後在 팔도_PALDO 晚餐。"
    ],
    notes: [
      "皮諾美術館這天是主景點，重點看 Fujiko Nakaya 霧雕塑。",
      "小皇宮常設展免費，若想加看特展才需要另購票。",
      "PALDO 五人建議提前訂位，並保留晚餐移動時間。"
    ],
    links: [
      ["Petite Île Boulangerie", "Petite Île Boulangerie Paris"],
      ["Merci", "Merci 111 Boulevard Beaumarchais Paris"],
      ["Bourse de Commerce – Pinault Collection", "Bourse de Commerce Pinault Collection Paris"],
      ["Phở Bánh Cuốn 14 Opéra", "Phở Bánh Cuốn 14 Opéra Paris"],
      ["Petit Palais", "Petit Palais Paris"],
      ["팔도_PALDO", "팔도_PALDO Paris"]
    ]
  },
  "8/15（六，法國國定假日）瑪黑區｜街區散步與彈性購物": {
    headline: "瑪黑區散步與購物，早午餐吃 Breizh Café，下午 Cortado 與孚日廣場休息，晚上 Freddy’s",
    overview: [
      "10:30–12:00 先走 Hôtel de Sully 外觀、Rue Saint-Antoine 與 Village Saint-Paul。",
      "12:00–13:30 在 Breizh Café 吃早午餐。",
      "13:30–15:30 留給 Rue Vieille du Temple、Rue des Francs Bourgeois、Rue des Rosiers 散步與小店巡遊。",
      "15:30–16:15 前往 Cortado 喝咖啡休息。",
      "16:15–17:15 到 Place des Vosges 放慢休息，視體力調整停留時間。",
      "19:00 後在 Freddy’s 晚餐。"
    ],
    notes: [
      "8/15 是法國國定假日，餐廳營業狀況先查好，最好不要靠臨時決定。",
      "Breizh Café 與 Freddy’s 建議先訂位，尤其五人同行不適合完全靠現場候位。",
      "Rue des Rosiers 一帶週六加國定假日變數大，下午逛街路線保留彈性即可。"
    ],
    links: [
      ["Hôtel de Sully", "Hôtel de Sully Paris"],
      ["Rue Saint-Antoine", "Rue Saint-Antoine Paris"],
      ["Village Saint-Paul", "Village Saint-Paul Paris"],
      ["Breizh Café", "Breizh Café Paris"],
      ["Rue Vieille du Temple", "Rue Vieille du Temple Paris"],
      ["Rue des Francs Bourgeois", "Rue des Francs Bourgeois Paris"],
      ["Rue des Rosiers", "Rue des Rosiers Paris"],
      ["Cortado", "Cortado Paris"],
      ["Place des Vosges", "Place des Vosges Paris"],
      ["Freddy’s", "Freddy’s Paris"]
    ]
  },
  "8/16（日）FAUNA｜奧塞博物館｜巴黎鐵塔景觀": {
    headline: "早上吃 FAUNA，接著參觀奧塞美術館，傍晚到鐵塔周邊觀賞日景與日落後景色",
    overview: [
      "10:00–11:15 前往 FAUNA 吃早午餐。",
      "12:00–15:00 參觀 Musée d'Orsay，先看五樓印象派，再依體力補重點展區。",
      "15:00–17:30 奧塞周邊短散步、咖啡或回飯店休息，保留傍晚體力。",
      "17:30–18:30 晚餐待定，可視當天體力在鐵塔周邊或飯店附近簡單用餐。",
      "18:30–21:15 在 Champ de Mars 或 Trocadéro 一帶觀賞艾菲爾鐵塔日景、日落後景色與點燈。"
    ],
    notes: [
      "FAUNA 建議先確認週日營業與可訂位時段，若開門時間較晚，奧塞入場時間需同步順延。",
      "這天不安排進艾菲爾鐵塔，重點是旁邊公園與觀景點的日景、日落後藍調時刻與夜間點燈。",
      "若當天已走很多，晚間只留 Champ de Mars 或 Trocadéro 其中一側即可，不必兩邊都跑。"
    ],
    links: [
      ["FAUNA", "FAUNA Paris"],
      ["Musée d'Orsay", "Musée d'Orsay Paris"],
      ["Champ de Mars", "Champ de Mars Paris"],
      ["艾菲爾鐵塔", "Eiffel Tower Paris"],
      ["Trocadéro", "Trocadéro Paris"]
    ]
  },
  "8/17（一）巴黎軍事博物館｜塞納河遊船": {
    headline: "上午看榮軍院與拿破崙墓，下午休息整理，晚上搭塞納河遊船",
    overview: [
      "10:00–13:00 參觀巴黎軍事博物館、圓頂教堂與拿破崙墓。",
      "13:15–14:30 在 Rue Cler 或 Invalides 周邊午餐。",
      "14:30–16:30 回飯店休息與整理行李。",
      "17:30–19:00 在鐵塔或碼頭附近吃晚餐。",
      "19:45–21:00 到 Bateaux Parisiens 鐵塔碼頭搭塞納河遊船。"
    ],
    notes: [
      "這天重點是保留體力給隔天早班機，下午不要再塞跨區景點。",
      "遊船建議抓 20:30 或 21:00 左右，不必拖到最晚班。",
      "若晚餐時間被碼頭排隊壓縮，就改成簡單用餐即可。"
    ],
    links: [
      ["巴黎軍事博物館", "Musée de l'Armée Paris"],
      ["圓頂教堂", "Dôme des Invalides Paris"],
      ["拿破崙墓", "Napoleon Tomb Paris"],
      ["Rue Cler", "Rue Cler Paris"],
      ["Invalides", "Invalides Paris"],
      ["Bateaux Parisiens", "Bateaux Parisiens Eiffel Tower"]
    ]
  },
  "8/18（二）巴黎返台": {
    headline: "清晨前往 CDG，搭長榮回台",
    overview: [
      "06:45–07:00 自 Hôtel Magenta 38 出發前往 CDG Terminal 1。",
      "11:20 搭乘 BR88 離開巴黎，隔日 07:00 抵達台灣。"
    ],
    notes: [
      "若五人同行且都有大行李，預約車時需指定 6 人座以上。",
      "長榮在 CDG 的報到櫃檯 08:00 開放，建議保守抓機場作業時間。"
    ],
    links: [
      ["Hôtel Magenta 38", "Hotel Magenta 38 Paris"],
      ["CDG Terminal 1", "Charles de Gaulle Airport Terminal 1"]
    ]
  }
};
